"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# --------------------------------------------------------------
# BASE & ENV
# --------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# You should set these environment variables in production
# For example:
# SECRET_KEY=<your-production-secret>
# DEBUG=False
# ALLOWED_HOSTS=".example.com,localhost"
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-dev-key")
DEBUG = os.environ.get("DEBUG", "True") == "True"

# ALLOWED_HOSTS should be a comma-separated list in production
# e.g. ALLOWED_HOSTS="your-domain.com,your-other-domain.com"
# Retrieve the Railway public domain from the environment variable
RAILWAY_PUBLIC_DOMAIN = os.environ.get("RAILWAY_PUBLIC_DOMAIN")

if RAILWAY_PUBLIC_DOMAIN:
    # Production settings: use Railway's public domain
    ALLOWED_HOSTS = [RAILWAY_PUBLIC_DOMAIN]
    CSRF_TRUSTED_ORIGINS = [f"https://{RAILWAY_PUBLIC_DOMAIN}"]
    PUBLIC_URL = f"https://{RAILWAY_PUBLIC_DOMAIN}"
else:
    # Development settings: default to localhost
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
    CSRF_TRUSTED_ORIGINS = ["http://localhost", "http://127.0.0.1"]
    PUBLIC_URL = "http://localhost:8000"
# If you'd like to load from an env variable, do:
# CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")

# --------------------------------------------------------------
# APPLICATION DEFINITION
# --------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    ## Required by django-allauth
    'django.contrib.sites',  # Must be added

   
    # ... your other apps
    'cloudinary',
    'cloudinary_storage',


    # allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Other apps...
    'django_bootstrap5',
    #'django_bootstrap_icons'
    "crispy_forms",
    "crispy_bootstrap5",

    # My apps

    'home',
    'users.apps.UsersConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise middleware for serving static files in production
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # <-- Add this line
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # your custom templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'mysite.wsgi.application'

# --------------------------------------------------------------
# DATABASE CONFIGURATION
# --------------------------------------------------------------
# By default, uses Postgres settings from environment variables
# If you want a fallback for local dev, change the defaults below

import dj_database_url

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ["PGDATABASE"],
        'USER': os.environ["PGUSER"],
        'PASSWORD': os.environ["PGPASSWORD"],
        'HOST': os.environ["PGHOST"],
        'PORT': os.environ["PGPORT"],
    }
}'''

# --------------------------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --------------------------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --------------------------------------------------------------
# STATIC FILES
# --------------------------------------------------------------
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Enable Gzip or Brotli compression and cache headers with WhiteNoise
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# --------------------------------------------------------------
# DEFAULT PRIMARY KEY FIELD TYPE
# --------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




##### Allauth settings #####

SITE_ID = 1
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth backend
)

# Redirect URLs

AUTH_USER_MODEL = 'users.CustomUser'

#CDN Cloudinary
""" 
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# Use Cloudinary for media files
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# If you want to serve static files via Cloudinary as well, you can set:
STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'

# Your Cloudinary URLs will be provided automatically
MEDIA_URL = f"https://res.cloudinary.com/{os.getenv('CLOUDINARY_CLOUD_NAME')}/"

"""




LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

### Allaouth settings ###
#ACCOUNT_AUTHENTICATION_METHOD = 'email'
#ACCOUNT_USER_MODEL_USERNAME_FIELD 
#ACCOUNT_EMAIL_REQUIRED = True
#ACCOUNT_USERNAME_REQUIRED = False

###
# Allauth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # or "optional" based on your needs
ACCOUNT_AUTHENTICATION_METHOD = "username_email"  # or "email" if you prefer
LOGIN_REDIRECT_URL = '/'
#ACCOUNT_SIGNUP_FORM_CLASS = 'your_app.forms.YourCustomSignupForm'






# Email verification (set to "none" for development)
ACCOUNT_EMAIL_VERIFICATION = "none"  
ACCOUNT_EMAIL_REQUIRED = True

# Optional: Customize the signup form fields, etc.
ACCOUNT_USERNAME_REQUIRED = False


ACCOUNT_FORMS = {'signup': 'users.forms.CustomSignupForm'}



CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


if not DEBUG:
    # Local development: use console email backend so emails are printed in the terminal.
    # Production on Railway: use the SMTP backend with environment variables set on Railway.
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# --------------------------------------------------------------
# SECURITY RECOMMENDATIONS (Production)
# --------------------------------------------------------------
# If you are behind a reverse proxy that uses HTTPS, set this:
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# If you want to enforce HTTPS in production (recommended):
# SECURE_SSL_REDIRECT = not DEBUG

# If you need HSTS:
# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# X-Frame-Options sets if your site can be embedded in an iframe
# X_FRAME_OPTIONS = "DENY"
