# Generated by Django 5.2.8 on 2025-11-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('rg_num', models.CharField(blank=True, max_length=20)),
                ('rg_data', models.DateField(blank=True, null=True)),
                ('rg_orgao', models.CharField(blank=True, max_length=50)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_corretor', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
